---
apiVersion: v1
kind: Namespace
metadata:
  name: file-uploader-rwx
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: file-uploader
  name: file-uploader
  namespace: file-uploader-rwx
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: file-uploader
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: file-uploader
    spec:
      containers:
      - image: quay.io/vcppds7878/file-uploader@sha256:b59a6f3bedceb8569b2d9ad6d043425331ad2aeafaca3a83075fdb26a6406a30
        imagePullPolicy: IfNotPresent
        name: file-uploader
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app-root/src/uploaded
          name: my-shared-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: my-shared-storage
        persistentVolumeClaim:
          claimName: file-uploader-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-uploader-data
  namespace: file-uploader-rwx
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: file-uploader
  name: file-uploader
  namespace: file-uploader-rwx
spec:
  type: LoadBalancer
  ports:
  - name: 8080-tcp
    port: 8080
  - name: 8443-tcp
    port: 8443
  selector:
    deployment: file-uploader
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: file-uploader
  name: file-uploader
  namespace: file-uploader-rwx
spec:
  host: ''
  to:
    kind: Service
    name: file-uploader
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
